<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-11-22 19:16
=======
# Generated by Django 3.1.7 on 2021-11-22 19:10
>>>>>>> urim11234

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Genre_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('ost', models.CharField(max_length=100)),
                ('running_time', models.IntegerField(default=100)),
                ('grade', models.FloatField(default=5.0)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=300)),
                ('genres', models.ManyToManyField(related_name='genre_movies', to='movies.Genre')),
            ],
        ),
    ]
