# Generated by Django 3.1.7 on 2021-11-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=300)),
                ('ost', models.TextField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
