# Generated by Django 3.1.7 on 2021-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_movie',
            name='ost',
            field=models.CharField(max_length=100),
        ),
    ]
