# Generated by Django 3.1.7 on 2021-11-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211119_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_movie',
            name='genres',
            field=models.ManyToManyField(related_name='genre_movies', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.Genre'),
        ),
    ]
