# Generated by Django 3.1.7 on 2021-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211119_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre_movie',
            name='grade',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='genre_movie',
            name='running_time',
            field=models.IntegerField(default=100),
        ),
    ]
